const welcome=document.querySelector('#welcome'),gift=document.querySelector('#gift'),openButton=document.querySelector('#openButton'),messageButton=document.querySelector('#messageButton'),letter=document.querySelector('#letter'),closeLetter=document.querySelector('#closeLetter'),againButton=document.querySelector('#againButton'),soundButton=document.querySelector('#soundButton'),musicPlayer=document.querySelector('#musicPlayer');let musicOn=false;
const stars=document.querySelector('#stars');for(let i=0;i<54;i++){const s=document.createElement('i');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.setProperty('--d',(2+Math.random()*4)+'s');s.style.setProperty('--delay',(-Math.random()*5)+'s');stars.appendChild(s)}
const canvas=document.querySelector('#particles'),ctx=canvas.getContext('2d');let motes=Array.from({length:76},()=>({x:Math.random()*innerWidth,y:innerHeight+Math.random()*innerHeight,r:.6+Math.random()*2,v:.2+Math.random()*.75,w:Math.random()*6,a:.15+Math.random()*.7})),running=false;
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function animate(){if(!running)return;ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of motes){p.y-=p.v;p.x+=Math.sin(p.y/45+p.w)*.3;if(p.y<-10){p.y=innerHeight+10;p.x=Math.random()*innerWidth}ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='rgba(255,215,75,'+p.a+')';ctx.shadowColor='#ffd94e';ctx.shadowBlur=10;ctx.fill()}requestAnimationFrame(animate)}
let audioCtx;function chime(){try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();[523.25,659.25,783.99].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;g.gain.setValueAtTime(.035,audioCtx.currentTime+i*.12);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+i*.12+1.4);o.connect(g).connect(audioCtx.destination);o.start(audioCtx.currentTime+i*.12);o.stop(audioCtx.currentTime+i*.12+1.5)})}catch(e){}}
function music(command){musicPlayer.contentWindow?.postMessage(JSON.stringify({event:'command',func:command,args:[]}), '*')}function setMusic(on){musicOn=on;music(on?'playVideo':'pauseVideo');soundButton.classList.toggle('on',on);soundButton.setAttribute('aria-pressed',String(on));soundButton.textContent=on?'♫':'♪'}
function reveal(){welcome.classList.add('hide');gift.setAttribute('aria-hidden','false');setMusic(true);setTimeout(()=>{gift.classList.add('reveal');running=true;animate();chime()},550)}
openButton.addEventListener('click',reveal);messageButton.addEventListener('click',()=>{letter.showModal();chime()});closeLetter.addEventListener('click',()=>letter.close());letter.addEventListener('click',e=>{if(e.target===letter)letter.close()});againButton.addEventListener('click',()=>{letter.close();gift.classList.remove('reveal');void gift.offsetWidth;gift.classList.add('reveal');chime()});soundButton.addEventListener('click',()=>setMusic(!musicOn));
